In [5]:
#Probability of survival
import pandas as pd
df = pd.read_csv("titanic.csv")
df.head()

,PassengerId,Name,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Survived
0,1,"Braund, Mr. Owen Harris",3,male,22.0,1,0,A/5 21171,7.2500,NaN,S,0
1,2,"Cumings, Mrs. John Bradley (Florence Briggs Th...",1,female,38.0,1,0,PC 17599,71.2833,C85,C,1
2,3,"Heikkinen, Miss. Laina",3,female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,1
3,4,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",1,female,35.0,1,0,113803,53.1000,C123,S,1
4,5,"Allen, Mr. William Henry",3,male,35.0,0,0,373450,8.0500,NaN,S,0

In [6]:
df.drop(["PassengerId","Name","SibSp", "Parch","Ticket","Cabin","Embarked"], axis = 'columns', inplace=True)
df.head()

   Pclass     Sex   Age     Fare  Survived
0       3    male  22.0   7.2500         0
1       1  female  38.0  71.2833         1
2       3  female  26.0   7.9250         1
3       1  female  35.0  53.1000         1
4       3    male  35.0   8.0500         0

In [8]:
#SETTING TARGTS nd inputs
target = df.Survived
inputs = df.drop("Survived", axis ="columns")

In [9]:
#CREATING DUMMIES FOR SEX
dummies = pd.get_dummies(inputs.Sex)
dummies.head(3)

   female   male
0   False   True
1    True  False
2    True  False

In [12]:
#ADDING DUMMIES TO DF
inputs = pd.concat([inputs,dummies], axis = 'columns')
inputs.head()

   Pclass     Sex   Age     Fare  female   male
0       3    male  22.0   7.2500   False   True
1       1  female  38.0  71.2833    True  False
2       3  female  26.0   7.9250    True  False
3       1  female  35.0  53.1000    True  False
4       3    male  35.0   8.0500   False   True

In [14]:
#removing sex column
inputs.drop('Sex', axis='columns', inplace = True)
inputs.head()

   Pclass   Age     Fare  female   male
0       3  22.0   7.2500   False   True
1       1  38.0  71.2833    True  False
2       3  26.0   7.9250    True  False
3       1  35.0  53.1000    True  False
4       3  35.0   8.0500   False   True

In [15]:
#CHECKING FOR NULL VALUES IN INPUTS
inputs.columns[inputs.isna().any()]

Index(['Age'], dtype='object')

In [18]:
inputs.Age[:10]

0    22.0
1    38.0
2    26.0
3    35.0
4    35.0
5     NaN
6    54.0
7     2.0
8    27.0
9    14.0
Name: Age, dtype: float64

In [23]:
#INSERTING MEAN TO THE NULL VALUES
inputs.Age = inputs.Age.fillna(inputs.Age.mean())
inputs.Age[:10]

0    22.000000
1    38.000000
2    26.000000
3    35.000000
4    35.000000
5    29.699118
6    54.000000
7     2.000000
8    27.000000
9    14.000000
Name: Age, dtype: float64

In [41]:
#TRAIN TEST SPLIT
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(inputs,target,test_size=0.3)

In [25]:
len(x_train)

623

In [26]:
len(x_test)

268

In [42]:
#NAIVE BAYES ALGORITHM APPLY
from sklearn.naive_bayes import GaussianNB
model = GaussianNB()
model.fit(x_train,y_train)

GaussianNB()

In [43]:
model.score(x_test,y_test)

0.7835820895522388

In [44]:
x_test[:10]

     Pclass        Age      Fare  female   male
566       3  19.000000    7.8958   False   True
799       3  30.000000   24.1500    True  False
857       1  51.000000   26.5500   False   True
581       1  39.000000  110.8833    True  False
760       3  29.699118   14.5000   False   True
814       3  30.500000    8.0500   False   True
99        2  34.000000   26.0000   False   True
278       3   7.000000   29.1250   False   True
408       3  21.000000    7.7750   False   True
171       3   4.000000   29.1250   False   True

In [50]:
y_test[:10]

566    0
799    0
857    1
581    1
760    0
814    0
99     0
278    0
408    0
171    0
Name: Survived, dtype: int64

In [49]:
model.predict(x_test[:10])

array([0, 1, 0, 1, 0, 0, 0, 0, 0, 0])

In [47]:
model.predict_proba(x_test[:10])

array([[9.90217938e-01, 9.78206161e-03],
       [1.01572452e-01, 8.98427548e-01],
       [8.94040879e-01, 1.05959121e-01],
       [3.21279556e-04, 9.99678720e-01],
       [9.92175955e-01, 7.82404495e-03],
       [9.92084500e-01, 7.91549952e-03],
       [9.80421756e-01, 1.95782439e-02],
       [9.83196823e-01, 1.68031770e-02],
       [9.90732475e-01, 9.26752450e-03],
       [9.80219264e-01, 1.97807355e-02]])